version: '2'
#
# Compose definitions for stack2 common containers
#
# Assumes docker for mac.
#
services:
  syslog:
    image: "devopscenter/syslog:${CONTAINER_VERSION}"
    env_file:
        - "APP_NAME-ENV.env"

  pgmaster-1:
    image: "devopscenter/db_postgres:${CONTAINER_VERSION}"
    ports:
      - "5432:5432"
    env_file:
        - "APP_NAME-ENV.env"
    volumes:
      - pg-db:/media/data/postgres/
 
#pgstandby-1:
#  image: "devopscenter/db_postgres-standby:${CONTAINER_VERSION}"
#  links:
#    - "pgsmaster-1"
#  env_file:
#    - local.env
#  environment:
#    - POSTGRES_CONFIG_FILE=/media/data/postgres/db/pgdata/postgresql.conf


  redismaster:
    image: "devopscenter/db_redis:${CONTAINER_VERSION}"
    env_file:
        - "APP_NAME-ENV.env"
    ports:
      - "6379:6379"
    volumes:
      - redis:/media/data/redis

#redisstandby:
#  image: devopscenter/db_redis-standby

# Must include all named volumes in V2 compose file format.
volumes:
  redis:
  pg-db:
