version: '2'

services:
    web:
        container_name: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_web-1"
        hostname: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_web-1"
        image: "devopscenter/DC_UNIQUE_ID.web-debug:${dcSTACK_VERSION}"
        ports:
            - "${DOCKER_WEB_1_PORT_80}"
            - "${DOCKER_WEB_1_PORT_8000}"
            - "${DOCKER_WEB_1_PORT_443}"
        links:
            - "pgmaster-1"
        volumes:
            - "${dcAPP}:/data/deploy/current"
            - "/wheelhouse"
            - "${dcDATA}:/dataload"
            - "${dcUTILS}:/utils"
            - "${APP_UTILS_CONFIG}:/app-utils/conf"
            - "${APP_UTILS_KEYS}:/app-utils/keys"
        working_dir: "/data/deploy/current"
        env_file:
            - "${GENERATED_ENV_FILE}"
        volumes_from:
            - syslog
        networks:
            local_network:
                ipv4_address: "${DOCKER_WEB_1_IP}"

    pgmaster-1:
        container_name: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_pgmaster-1"
        hostname: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_pgmaster-1"
        image: "devopscenter/db_postgres:${dcSTACK_VERSION}"
        ports:
            - "${DOCKER_PGMASTER_PORT_5432}"
        env_file:
            - "${GENERATED_ENV_FILE}"
        volumes:
            - pg-db:/media/data/postgres/
            - "${dcUTILS}:/utils"
            - "${APP_UTILS_CONFIG}:/app-utils/conf"
            - "${APP_UTILS_KEYS}:/app-utils/keys"
        working_dir: "/data/deploy/current"
        volumes_from:
            - syslog
        networks:
            local_network:
                ipv4_address: "${DOCKER_PGMASTER_IP}"


    syslog:
        container_name: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_syslog"
        hostname: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_syslog"
        image: "devopscenter/syslog:${dcSTACK_VERSION}"
        env_file:
            - "${GENERATED_ENV_FILE}"
        environment:
            LOG_NAME:
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_PROTO}://${SYSLOG_SERVER}:${SYSLOG_PORT}"
                syslog-facility: local0
                env: LOG_NAME
                tag: "{{ (.ExtraAttributes nil).LOG_NAME}} {{.Name}}"
        networks:
            local_network:
                ipv4_address: "${DOCKER_SYSLOG_IP}"

# Must include all named volumes in V2 compose file format.
volumes:
    pg-db:
