version: '2'

services:
    web:
        container_name: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_web-1"
        hostname: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_web-1"
        image: "devopscenter/DC_UNIQUE_ID.web:${dcSTACK_VERSION}"
        ports:
            - "${DOCKER_STATIC_IP_1}:80:80"
            - "${DOCKER_STATIC_IP_1}:8000:8000"
            - "${DOCKER_STATIC_IP_1}:443:443"
        links:
            - "pgmaster-1"
            - "worker"
            - "redismaster"
        volumes:
            - "${dcAPP}:/data/deploy/current"
            - "/wheelhouse"
            - "${dcDATA}:/dataload"
            - "${dcUTILS}:/utils"
            - "${APP_UTILS_CONFIG}:/app-utils/conf"
            - "${APP_UTILS_KEYS}:/app-utils/keys"
        working_dir: "/data/deploy/current"
        env_file:
            - "${GENERATED_ENV_FILE}"
        volumes_from:
            - syslog
        networks:
            local_network:
                ipv4_address: "${DOCKER_STATIC_IP_1}"
    worker:
        container_name: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_worker-1"
        hostname: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_worker-1"
        image: "devopscenter/DC_UNIQUE_ID.worker:${dcSTACK_VERSION}"
        ports:
            - "${DOCKER_STATIC_IP_2}:5555:5555"
        links:
            - "pgmaster-1"
            - "redismaster"
        volumes:
            - "${dcAPP}:/data/deploy/current"
            - /wheelhouse
            - "${dcUTILS}:/utils"
            - "${APP_UTILS_CONFIG}:/app-utils/conf"
            - "${APP_UTILS_KEYS}:/app-utils/keys"
        working_dir: "/data/deploy/current"
        env_file:
            - "${GENERATED_ENV_FILE}"
        volumes_from:
            - syslog
        networks:
            local_network:
                ipv4_address: "${DOCKER_STATIC_IP_2}"

    pgmaster-1:
        container_name: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_pgmaster-1"
        hostname: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_pgmaster-1"
        image: "devopscenter/db_postgres:${dcSTACK_VERSION}"
        ports:
            - "${DOCKER_STATIC_IP_3}:5432:5432"
        env_file:
            - "${GENERATED_ENV_FILE}"
        volumes:
            - pg-db:/media/data/postgres/
            - "${dcUTILS}:/utils"
            - "${APP_UTILS_CONFIG}:/app-utils/conf"
            - "${APP_UTILS_KEYS}:/app-utils/keys"
        working_dir: "/data/deploy/current"
        volumes_from:
            - syslog
        networks:
            local_network:
                ipv4_address: "${DOCKER_STATIC_IP_3}"


    redismaster:
        container_name: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_redismaster"
        hostname: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_redismaster"
        image: "devopscenter/db_redis:${dcSTACK_VERSION}"
        env_file:
            - "${GENERATED_ENV_FILE}"
        ports:
            - "${DOCKER_STATIC_IP_4}:6379:6379"
        volumes:
            - redis:/media/data/redis
            - "${dcUTILS}:/utils"
            - "${APP_UTILS_CONFIG}:/app-utils/conf"
        working_dir: "/data/deploy/current"
        volumes_from:
            - syslog
        networks:
            local_network:
                ipv4_address: "${DOCKER_STATIC_IP_4}"

    syslog:
        container_name: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_syslog"
        hostname: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_syslog"
        image: "devopscenter/syslog:${dcSTACK_VERSION}"
        env_file:
            - "${GENERATED_ENV_FILE}"
        environment:
            LOG_NAME:
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_PROTO}://${SYSLOG_SERVER}:${SYSLOG_PORT}"
                syslog-facility: local0
                env: LOG_NAME
                tag: "{{ (.ExtraAttributes nil).LOG_NAME}} {{.Name}}"
        networks:
            local_network:
                ipv4_address: "${DOCKER_STATIC_IP_5}"

# user defined network
networks:
      local_network:
          driver: bridge
          ipam:
              driver: default
              config:
                -  subnet: "${DOCKER_SUBNET_TO_USE}"
  ~
# Must include all named volumes in V2 compose file format.
volumes:
    redis:
    pg-db:
